import type { TranslationOptions } from "./index";

/**
 * Register your messages here to get type-checked translation keys.
 *
 * Augment it from the package you import hooks from (`@intl-party/nextjs`,
 * `@intl-party/react`, or `@intl-party/core`), usually in an
 * `intl-party.d.ts` generated by `intl-party generate --types`:
 *
 * ```ts
 * import type common from "./messages/en/common.json";
 *
 * declare module "@intl-party/nextjs" {
 *   interface IntlPartyRegister {
 *     messages: { common: typeof common };
 *   }
 * }
 * ```
 *
 * Until it is augmented, namespaces and keys are plain strings.
 */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface IntlPartyRegister {}

type RegisteredMessages = IntlPartyRegister extends { messages: infer M }
  ? M
  : never;

type IsRegistered = [RegisteredMessages] extends [never] ? false : true;

/** Dot-separated paths to every string leaf of a messages object. */
export type MessageKeys<T, Prefix extends string = ""> = {
  [K in keyof T & string]: T[K] extends readonly unknown[]
    ? `${Prefix}${K}`
    : T[K] extends object
      ? MessageKeys<T[K], `${Prefix}${K}.`>
      : `${Prefix}${K}`;
}[keyof T & string];

/** A registered namespace, or any string when nothing is registered. */
export type RegisteredNamespace = IsRegistered extends true
  ? keyof RegisteredMessages & string
  : string;

/** Keys valid in namespace `N`, or any string when nothing is registered. */
export type NamespaceKey<N extends string> = IsRegistered extends true
  ? N extends keyof RegisteredMessages
    ? MessageKeys<RegisteredMessages[N]>
    : never
  : string;

/** Keys valid in any registered namespace. */
export type AnyNamespaceKey = IsRegistered extends true
  ? { [N in RegisteredNamespace]: NamespaceKey<N> }[RegisteredNamespace]
  : string;

/**
 * Keys accepted by a translator for namespace `N`. With no namespace
 * (`N` = never) any registered namespace's keys are accepted, matching
 * `useTranslations()` falling back to the current namespace at runtime.
 */
export type TranslationKeyFor<N extends string> = [N] extends [never]
  ? AnyNamespaceKey
  : NamespaceKey<N>;

/** A translation function whose keys are limited to `Key`. */
export type ScopedTranslationFunction<Key extends string = string> = (
  key: Key,
  options?: TranslationOptions,
) => string;
