// Generated by @intl-party/cli - do not edit.
// Registers your messages so translation keys are type-checked.
// Re-run `intl-party generate --types` after adding or removing a namespace.
import type ns0_common from "./messages/en/common.json";

declare module "@intl-party/nextjs" {
  interface IntlPartyRegister {
    messages: {
      "common": typeof ns0_common;
    };
  }
}
