/**
 * createSetup — the one-call Next.js setup documented in the README and
 * generated by `intl-party nextjs --init`.
 *
 * It is a thin layer over the lower-level building blocks exported from this
 * package (createI18nMiddleware, loadMessagesForLocale, the client Provider),
 * wired together from a single `intl-party.config.ts` object.
 */

import type { Locale, Namespace } from "@intl-party/core";
import { createI18nMiddleware, createLocaleMatcher } from "./middleware/index";
import { loadMessagesForLocale } from "./messages";
import { detectLocaleFromHeaders, type HeadersLike } from "./shared/detect";
import { detectAvailableNamespaces } from "./server/utils";
// Imported through the package's own "./client" export (kept external by the
// build) so the "use client" boundary survives bundling: server components
// that render `Provider` get a client reference, not an inlined copy.
import { Provider } from "@intl-party/nextjs/client";

export interface SetupConfig {
  locales: Locale[];
  defaultLocale: Locale;
  /** Path to the messages directory, relative to the project root. Default: "./messages" */
  messages?: string;
  /** Namespaces to load. Default: every JSON file in the messages directory. */
  namespaces?: Namespace[];
  /** Whether URLs carry a locale prefix. Default: "never" (clean URLs). */
  localePrefix?: "always" | "as-needed" | "never";
  /** Cookie that stores the user's locale choice. Default: "INTL_LOCALE" */
  cookieName?: string;
}

export interface SetupResult {
  /** Next.js middleware that detects the locale and stores it in a cookie. */
  middleware: ReturnType<typeof createI18nMiddleware>;
  /** Matcher config for the middleware. */
  middlewareConfig: { matcher: string[] };
  /** Resolves the current request's locale (cookie, then Accept-Language). */
  getLocale: () => Promise<Locale>;
  /**
   * Loads messages for `locale`, keyed by locale so the result can be passed
   * straight to `<Provider initialMessages={...}>`.
   */
  getMessages: (
    locale: Locale,
  ) => Promise<Record<Locale, Record<Namespace, unknown>>>;
  /** Client provider; render it in your root layout. */
  Provider: typeof Provider;
}

const DEFAULT_COOKIE_NAME = "INTL_LOCALE";

export function createSetup(config: SetupConfig): SetupResult {
  const {
    locales,
    defaultLocale,
    messages: messagesPath = "./messages",
    namespaces,
    localePrefix = "never",
    cookieName = DEFAULT_COOKIE_NAME,
  } = config;

  const middleware = createI18nMiddleware({
    locales,
    defaultLocale,
    localePrefix,
    cookieName,
    // Clean URLs: never redirect or read the locale from the path.
    ...(localePrefix === "never" && {
      redirectStrategy: "none" as const,
      detectFromPath: false,
    }),
  });

  const getLocale = async (): Promise<Locale> => {
    // Imported lazily so middleware bundles never pull in next/headers.
    const { headers } = await import("next/headers");
    // headers() returns a Promise in Next 15+; awaiting the plain object on
    // Next 13/14 is a no-op.
    const headersList = await (headers() as unknown as Promise<HeadersLike>);
    return detectLocaleFromHeaders(headersList, {
      locales,
      defaultLocale,
      cookieName,
    });
  };

  const getMessages = async (locale: Locale) => ({
    [locale]: await loadMessagesForLocale(locale, {
      messagesPath,
      // Detected per call (not cached) so new namespace files show up in dev.
      namespaces:
        namespaces ?? (await detectAvailableNamespaces([locale], messagesPath)),
    }),
  });

  return {
    middleware,
    middlewareConfig: { matcher: createLocaleMatcher() },
    getLocale,
    getMessages,
    Provider,
  };
}
